/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BusinessSupportRouteImport } from './routes/business/support'
import { Route as BusinessSubscriptionsRouteImport } from './routes/business/subscriptions'
import { Route as BusinessStaffRouteImport } from './routes/business/staff'
import { Route as BusinessSettingsRouteImport } from './routes/business/settings'
import { Route as BusinessServicesRouteImport } from './routes/business/services'
import { Route as BusinessReviewsRouteImport } from './routes/business/reviews'
import { Route as BusinessReportsRouteImport } from './routes/business/reports'
import { Route as BusinessReelsRouteImport } from './routes/business/reels'
import { Route as BusinessPosRouteImport } from './routes/business/pos'
import { Route as BusinessPaymentsRouteImport } from './routes/business/payments'
import { Route as BusinessPartnersRouteImport } from './routes/business/partners'
import { Route as BusinessPackagesRouteImport } from './routes/business/packages'
import { Route as BusinessOffersRouteImport } from './routes/business/offers'
import { Route as BusinessMembershipsRouteImport } from './routes/business/memberships'
import { Route as BusinessMarketingRouteImport } from './routes/business/marketing'
import { Route as BusinessLoyaltyReportRouteImport } from './routes/business/loyalty-report'
import { Route as BusinessLoyaltyRouteImport } from './routes/business/loyalty'
import { Route as BusinessInventoryRouteImport } from './routes/business/inventory'
import { Route as BusinessGiftCardsRouteImport } from './routes/business/gift-cards'
import { Route as BusinessExpensesRouteImport } from './routes/business/expenses'
import { Route as BusinessCustomersRouteImport } from './routes/business/customers'
import { Route as BusinessCalendarRouteImport } from './routes/business/calendar'
import { Route as BusinessBookingsRouteImport } from './routes/business/bookings'
import { Route as BusinessAcademyRouteImport } from './routes/business/academy'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSponsoredRouteImport } from './routes/admin/sponsored'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRefundsRouteImport } from './routes/admin/refunds'
import { Route as AdminReelsRouteImport } from './routes/admin/reels'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminLoyaltyRouteImport } from './routes/admin/loyalty'
import { Route as AdminGiftCardsRouteImport } from './routes/admin/gift-cards'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminBusinessesRouteImport } from './routes/admin/businesses'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'

const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BusinessSupportRoute = BusinessSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSubscriptionsRoute = BusinessSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessStaffRoute = BusinessStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSettingsRoute = BusinessSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessServicesRoute = BusinessServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessReviewsRoute = BusinessReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessReportsRoute = BusinessReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessReelsRoute = BusinessReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessPosRoute = BusinessPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessPaymentsRoute = BusinessPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessPartnersRoute = BusinessPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessPackagesRoute = BusinessPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessOffersRoute = BusinessOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessMembershipsRoute = BusinessMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessMarketingRoute = BusinessMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessLoyaltyReportRoute = BusinessLoyaltyReportRouteImport.update({
  id: '/loyalty-report',
  path: '/loyalty-report',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessLoyaltyRoute = BusinessLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessInventoryRoute = BusinessInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessGiftCardsRoute = BusinessGiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessExpensesRoute = BusinessExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessCustomersRoute = BusinessCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessCalendarRoute = BusinessCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessBookingsRoute = BusinessBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessAcademyRoute = BusinessAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => BusinessRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsoredRoute = AdminSponsoredRouteImport.update({
  id: '/sponsored',
  path: '/sponsored',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReelsRoute = AdminReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGiftCardsRoute = AdminGiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gift-cards': typeof AdminGiftCardsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reels': typeof AdminReelsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsored': typeof AdminSponsoredRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/business/academy': typeof BusinessAcademyRoute
  '/business/bookings': typeof BusinessBookingsRoute
  '/business/calendar': typeof BusinessCalendarRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/expenses': typeof BusinessExpensesRoute
  '/business/gift-cards': typeof BusinessGiftCardsRoute
  '/business/inventory': typeof BusinessInventoryRoute
  '/business/loyalty': typeof BusinessLoyaltyRoute
  '/business/loyalty-report': typeof BusinessLoyaltyReportRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/memberships': typeof BusinessMembershipsRoute
  '/business/offers': typeof BusinessOffersRoute
  '/business/packages': typeof BusinessPackagesRoute
  '/business/partners': typeof BusinessPartnersRoute
  '/business/payments': typeof BusinessPaymentsRoute
  '/business/pos': typeof BusinessPosRoute
  '/business/reels': typeof BusinessReelsRoute
  '/business/reports': typeof BusinessReportsRoute
  '/business/reviews': typeof BusinessReviewsRoute
  '/business/services': typeof BusinessServicesRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/staff': typeof BusinessStaffRoute
  '/business/subscriptions': typeof BusinessSubscriptionsRoute
  '/business/support': typeof BusinessSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gift-cards': typeof AdminGiftCardsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reels': typeof AdminReelsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsored': typeof AdminSponsoredRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/business/academy': typeof BusinessAcademyRoute
  '/business/bookings': typeof BusinessBookingsRoute
  '/business/calendar': typeof BusinessCalendarRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/expenses': typeof BusinessExpensesRoute
  '/business/gift-cards': typeof BusinessGiftCardsRoute
  '/business/inventory': typeof BusinessInventoryRoute
  '/business/loyalty': typeof BusinessLoyaltyRoute
  '/business/loyalty-report': typeof BusinessLoyaltyReportRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/memberships': typeof BusinessMembershipsRoute
  '/business/offers': typeof BusinessOffersRoute
  '/business/packages': typeof BusinessPackagesRoute
  '/business/partners': typeof BusinessPartnersRoute
  '/business/payments': typeof BusinessPaymentsRoute
  '/business/pos': typeof BusinessPosRoute
  '/business/reels': typeof BusinessReelsRoute
  '/business/reports': typeof BusinessReportsRoute
  '/business/reviews': typeof BusinessReviewsRoute
  '/business/services': typeof BusinessServicesRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/staff': typeof BusinessStaffRoute
  '/business/subscriptions': typeof BusinessSubscriptionsRoute
  '/business/support': typeof BusinessSupportRoute
  '/admin': typeof AdminIndexRoute
  '/business': typeof BusinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gift-cards': typeof AdminGiftCardsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reels': typeof AdminReelsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsored': typeof AdminSponsoredRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/business/academy': typeof BusinessAcademyRoute
  '/business/bookings': typeof BusinessBookingsRoute
  '/business/calendar': typeof BusinessCalendarRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/expenses': typeof BusinessExpensesRoute
  '/business/gift-cards': typeof BusinessGiftCardsRoute
  '/business/inventory': typeof BusinessInventoryRoute
  '/business/loyalty': typeof BusinessLoyaltyRoute
  '/business/loyalty-report': typeof BusinessLoyaltyReportRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/memberships': typeof BusinessMembershipsRoute
  '/business/offers': typeof BusinessOffersRoute
  '/business/packages': typeof BusinessPackagesRoute
  '/business/partners': typeof BusinessPartnersRoute
  '/business/payments': typeof BusinessPaymentsRoute
  '/business/pos': typeof BusinessPosRoute
  '/business/reels': typeof BusinessReelsRoute
  '/business/reports': typeof BusinessReportsRoute
  '/business/reviews': typeof BusinessReviewsRoute
  '/business/services': typeof BusinessServicesRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/staff': typeof BusinessStaffRoute
  '/business/subscriptions': typeof BusinessSubscriptionsRoute
  '/business/support': typeof BusinessSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/business'
    | '/admin/activity'
    | '/admin/admins'
    | '/admin/approvals'
    | '/admin/bookings'
    | '/admin/businesses'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/gift-cards'
    | '/admin/loyalty'
    | '/admin/offers'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reels'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/sponsored'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/business/academy'
    | '/business/bookings'
    | '/business/calendar'
    | '/business/customers'
    | '/business/expenses'
    | '/business/gift-cards'
    | '/business/inventory'
    | '/business/loyalty'
    | '/business/loyalty-report'
    | '/business/marketing'
    | '/business/memberships'
    | '/business/offers'
    | '/business/packages'
    | '/business/partners'
    | '/business/payments'
    | '/business/pos'
    | '/business/reels'
    | '/business/reports'
    | '/business/reviews'
    | '/business/services'
    | '/business/settings'
    | '/business/staff'
    | '/business/subscriptions'
    | '/business/support'
    | '/admin/'
    | '/business/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/activity'
    | '/admin/admins'
    | '/admin/approvals'
    | '/admin/bookings'
    | '/admin/businesses'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/gift-cards'
    | '/admin/loyalty'
    | '/admin/offers'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reels'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/sponsored'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/business/academy'
    | '/business/bookings'
    | '/business/calendar'
    | '/business/customers'
    | '/business/expenses'
    | '/business/gift-cards'
    | '/business/inventory'
    | '/business/loyalty'
    | '/business/loyalty-report'
    | '/business/marketing'
    | '/business/memberships'
    | '/business/offers'
    | '/business/packages'
    | '/business/partners'
    | '/business/payments'
    | '/business/pos'
    | '/business/reels'
    | '/business/reports'
    | '/business/reviews'
    | '/business/services'
    | '/business/settings'
    | '/business/staff'
    | '/business/subscriptions'
    | '/business/support'
    | '/admin'
    | '/business'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/business'
    | '/admin/activity'
    | '/admin/admins'
    | '/admin/approvals'
    | '/admin/bookings'
    | '/admin/businesses'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/gift-cards'
    | '/admin/loyalty'
    | '/admin/offers'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reels'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/sponsored'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/business/academy'
    | '/business/bookings'
    | '/business/calendar'
    | '/business/customers'
    | '/business/expenses'
    | '/business/gift-cards'
    | '/business/inventory'
    | '/business/loyalty'
    | '/business/loyalty-report'
    | '/business/marketing'
    | '/business/memberships'
    | '/business/offers'
    | '/business/packages'
    | '/business/partners'
    | '/business/payments'
    | '/business/pos'
    | '/business/reels'
    | '/business/reports'
    | '/business/reviews'
    | '/business/services'
    | '/business/settings'
    | '/business/staff'
    | '/business/subscriptions'
    | '/business/support'
    | '/admin/'
    | '/business/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/business/support': {
      id: '/business/support'
      path: '/support'
      fullPath: '/business/support'
      preLoaderRoute: typeof BusinessSupportRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/subscriptions': {
      id: '/business/subscriptions'
      path: '/subscriptions'
      fullPath: '/business/subscriptions'
      preLoaderRoute: typeof BusinessSubscriptionsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/staff': {
      id: '/business/staff'
      path: '/staff'
      fullPath: '/business/staff'
      preLoaderRoute: typeof BusinessStaffRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/settings': {
      id: '/business/settings'
      path: '/settings'
      fullPath: '/business/settings'
      preLoaderRoute: typeof BusinessSettingsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/services': {
      id: '/business/services'
      path: '/services'
      fullPath: '/business/services'
      preLoaderRoute: typeof BusinessServicesRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/reviews': {
      id: '/business/reviews'
      path: '/reviews'
      fullPath: '/business/reviews'
      preLoaderRoute: typeof BusinessReviewsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/reports': {
      id: '/business/reports'
      path: '/reports'
      fullPath: '/business/reports'
      preLoaderRoute: typeof BusinessReportsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/reels': {
      id: '/business/reels'
      path: '/reels'
      fullPath: '/business/reels'
      preLoaderRoute: typeof BusinessReelsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/pos': {
      id: '/business/pos'
      path: '/pos'
      fullPath: '/business/pos'
      preLoaderRoute: typeof BusinessPosRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/payments': {
      id: '/business/payments'
      path: '/payments'
      fullPath: '/business/payments'
      preLoaderRoute: typeof BusinessPaymentsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/partners': {
      id: '/business/partners'
      path: '/partners'
      fullPath: '/business/partners'
      preLoaderRoute: typeof BusinessPartnersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/packages': {
      id: '/business/packages'
      path: '/packages'
      fullPath: '/business/packages'
      preLoaderRoute: typeof BusinessPackagesRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/offers': {
      id: '/business/offers'
      path: '/offers'
      fullPath: '/business/offers'
      preLoaderRoute: typeof BusinessOffersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/memberships': {
      id: '/business/memberships'
      path: '/memberships'
      fullPath: '/business/memberships'
      preLoaderRoute: typeof BusinessMembershipsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/marketing': {
      id: '/business/marketing'
      path: '/marketing'
      fullPath: '/business/marketing'
      preLoaderRoute: typeof BusinessMarketingRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/loyalty-report': {
      id: '/business/loyalty-report'
      path: '/loyalty-report'
      fullPath: '/business/loyalty-report'
      preLoaderRoute: typeof BusinessLoyaltyReportRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/loyalty': {
      id: '/business/loyalty'
      path: '/loyalty'
      fullPath: '/business/loyalty'
      preLoaderRoute: typeof BusinessLoyaltyRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/inventory': {
      id: '/business/inventory'
      path: '/inventory'
      fullPath: '/business/inventory'
      preLoaderRoute: typeof BusinessInventoryRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/gift-cards': {
      id: '/business/gift-cards'
      path: '/gift-cards'
      fullPath: '/business/gift-cards'
      preLoaderRoute: typeof BusinessGiftCardsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/expenses': {
      id: '/business/expenses'
      path: '/expenses'
      fullPath: '/business/expenses'
      preLoaderRoute: typeof BusinessExpensesRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/customers': {
      id: '/business/customers'
      path: '/customers'
      fullPath: '/business/customers'
      preLoaderRoute: typeof BusinessCustomersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/calendar': {
      id: '/business/calendar'
      path: '/calendar'
      fullPath: '/business/calendar'
      preLoaderRoute: typeof BusinessCalendarRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/bookings': {
      id: '/business/bookings'
      path: '/bookings'
      fullPath: '/business/bookings'
      preLoaderRoute: typeof BusinessBookingsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/academy': {
      id: '/business/academy'
      path: '/academy'
      fullPath: '/business/academy'
      preLoaderRoute: typeof BusinessAcademyRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsored': {
      id: '/admin/sponsored'
      path: '/sponsored'
      fullPath: '/admin/sponsored'
      preLoaderRoute: typeof AdminSponsoredRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reels': {
      id: '/admin/reels'
      path: '/reels'
      fullPath: '/admin/reels'
      preLoaderRoute: typeof AdminReelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gift-cards': {
      id: '/admin/gift-cards'
      path: '/gift-cards'
      fullPath: '/admin/gift-cards'
      preLoaderRoute: typeof AdminGiftCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminGiftCardsRoute: typeof AdminGiftCardsRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReelsRoute: typeof AdminReelsRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSponsoredRoute: typeof AdminSponsoredRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminGiftCardsRoute: AdminGiftCardsRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReelsRoute: AdminReelsRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSponsoredRoute: AdminSponsoredRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BusinessRouteChildren {
  BusinessAcademyRoute: typeof BusinessAcademyRoute
  BusinessBookingsRoute: typeof BusinessBookingsRoute
  BusinessCalendarRoute: typeof BusinessCalendarRoute
  BusinessCustomersRoute: typeof BusinessCustomersRoute
  BusinessExpensesRoute: typeof BusinessExpensesRoute
  BusinessGiftCardsRoute: typeof BusinessGiftCardsRoute
  BusinessInventoryRoute: typeof BusinessInventoryRoute
  BusinessLoyaltyRoute: typeof BusinessLoyaltyRoute
  BusinessLoyaltyReportRoute: typeof BusinessLoyaltyReportRoute
  BusinessMarketingRoute: typeof BusinessMarketingRoute
  BusinessMembershipsRoute: typeof BusinessMembershipsRoute
  BusinessOffersRoute: typeof BusinessOffersRoute
  BusinessPackagesRoute: typeof BusinessPackagesRoute
  BusinessPartnersRoute: typeof BusinessPartnersRoute
  BusinessPaymentsRoute: typeof BusinessPaymentsRoute
  BusinessPosRoute: typeof BusinessPosRoute
  BusinessReelsRoute: typeof BusinessReelsRoute
  BusinessReportsRoute: typeof BusinessReportsRoute
  BusinessReviewsRoute: typeof BusinessReviewsRoute
  BusinessServicesRoute: typeof BusinessServicesRoute
  BusinessSettingsRoute: typeof BusinessSettingsRoute
  BusinessStaffRoute: typeof BusinessStaffRoute
  BusinessSubscriptionsRoute: typeof BusinessSubscriptionsRoute
  BusinessSupportRoute: typeof BusinessSupportRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessAcademyRoute: BusinessAcademyRoute,
  BusinessBookingsRoute: BusinessBookingsRoute,
  BusinessCalendarRoute: BusinessCalendarRoute,
  BusinessCustomersRoute: BusinessCustomersRoute,
  BusinessExpensesRoute: BusinessExpensesRoute,
  BusinessGiftCardsRoute: BusinessGiftCardsRoute,
  BusinessInventoryRoute: BusinessInventoryRoute,
  BusinessLoyaltyRoute: BusinessLoyaltyRoute,
  BusinessLoyaltyReportRoute: BusinessLoyaltyReportRoute,
  BusinessMarketingRoute: BusinessMarketingRoute,
  BusinessMembershipsRoute: BusinessMembershipsRoute,
  BusinessOffersRoute: BusinessOffersRoute,
  BusinessPackagesRoute: BusinessPackagesRoute,
  BusinessPartnersRoute: BusinessPartnersRoute,
  BusinessPaymentsRoute: BusinessPaymentsRoute,
  BusinessPosRoute: BusinessPosRoute,
  BusinessReelsRoute: BusinessReelsRoute,
  BusinessReportsRoute: BusinessReportsRoute,
  BusinessReviewsRoute: BusinessReviewsRoute,
  BusinessServicesRoute: BusinessServicesRoute,
  BusinessSettingsRoute: BusinessSettingsRoute,
  BusinessStaffRoute: BusinessStaffRoute,
  BusinessSubscriptionsRoute: BusinessSubscriptionsRoute,
  BusinessSupportRoute: BusinessSupportRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
